wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.5
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1690406989.027276
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 23
      4: 3.11.3
      5: 0.15.5
      8:
      - 2
      - 4
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: logits._type
      5: 1
      6:
      - 1
    - 1: logits.values
      5: 1
      6:
      - 1
    - 1: logits.bins
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
