name: train_model
on:
    push:
        branches: [master, main]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up Python 3.11.3
          uses: actions/setup-python@v4
          with:
            python-version: '3.11.3'
            cache: 'pip'
            cache-dependency-path: requirements.txt
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements_tests.txt
        - uses: iterative/setup-dvc@v1
        - name: Get data
          run: dvc pull
        - name: Train model
          run: python -m src.model.train_cml --input_dir data/processed --output_dir models
        - name: Write_report
          env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cat classification_report.txt >> report.md
            cml-publish confusion_matrix.png --md >> report.md
            cml-send-to-comment report.md
